FROM php:8.2-fpm

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libpq-dev \
    procps

# Очистка кеша
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Установка PHP расширений
RUN docker-php-ext-install pdo pdo_pgsql pgsql mbstring exif pcntl bcmath gd

# Установка Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Установка рабочей директории
WORKDIR /var/www/html

# Копирование файлов приложения
COPY --chown=www-data:www-data --chmod=www-data:www-data . .

# Установка прав
RUN chown -R www-data:www-data /var/www
RUN mkdir /var/www/html/storage && chown -R www-data:www-data /var/www/html/storage
RUN mkdir /var/www/html/bootstrap && chown -R www-data:www-data /var/www/html/bootstrap
RUN mkdir /var/www/html/bootstrap/cache && chown -R www-data:www-data /var/www/html/bootstrap/cache
RUN chmod -R 775 /var/www/html/storage
RUN chmod -R 775 /var/www/html/bootstrap/cache

# Установка переменной окружения для PHP
ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS="1" \
    PHP_OPCACHE_MAX_ACCELERATED_FILES="10000" \
    PHP_OPCACHE_MEMORY_CONSUMPTION="192" \
    PHP_OPCACHE_MAX_WASTED_PERCENTAGE="10"

# Включение opcache
RUN docker-php-ext-enable opcache

# Пользователь
USER www-data

EXPOSE 9000
CMD ["php-fpm"]
